# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170504_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='course_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='tutee_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
