# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20170504_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='tutor_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
