# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20170504_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tutor',
            field=models.BooleanField(default=True),
        ),
    ]
